"""
Main orchestrator for Personal AI Employee (Bronze Tier).

Entry point that initializes the vault, starts the file watcher,
and handles graceful shutdown.
"""

import os
import sys
import signal
from pathlib import Path

# Add src directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from dotenv import load_dotenv
from utils.logger import create_logger
from utils.vault_manager import create_vault_manager
from watchers.file_watcher import FileWatcher


class AIEmployeeOrchestrator:
    """Main orchestrator for AI Employee system."""

    def __init__(self):
        """Initialize orchestrator."""
        # Load environment variables
        load_dotenv()

        # Get configuration
        self.vault_path = os.getenv('VAULT_PATH')
        self.check_interval = int(os.getenv('CHECK_INTERVAL', '30'))
        self.log_level = os.getenv('LOG_LEVEL', 'INFO')
        self.dry_run = os.getenv('DRY_RUN', 'true').lower() == 'true'

        # Validate configuration
        if not self.vault_path:
            print("ERROR: VAULT_PATH not set in .env file")
            print("Please copy .env.example to .env and configure VAULT_PATH")
            sys.exit(1)

        # Initialize components
        self.logger = create_logger(self.vault_path, "Orchestrator", self.log_level)
        self.vault_manager = create_vault_manager(self.vault_path)
        self.watcher = None

        # Setup signal handlers for graceful shutdown
        signal.signal(signal.SIGINT, self._signal_handler)
        signal.signal(signal.SIGTERM, self._signal_handler)

    def _signal_handler(self, signum, frame):
        """Handle shutdown signals."""
        self.logger.info("Shutdown signal received")
        self.shutdown()
        sys.exit(0)

    def initialize_vault(self):
        """Initialize vault structure and templates."""
        self.logger.info(f"Initializing vault at: {self.vault_path}")

        # Validate vault path
        if not self.vault_manager.validate_vault():
            self.logger.info("Creating vault directory structure")
            self.vault_manager.create_vault_structure()
        else:
            self.logger.info("Vault directory exists, ensuring folder structure")
            self.vault_manager.create_vault_structure()

        # Create templates if they don't exist
        self._create_dashboard_template()
        self._create_handbook_template()

        self.logger.info("Vault initialization complete")

    def _create_dashboard_template(self):
        """Create Dashboard.md if it doesn't exist."""
        dashboard_path = Path(self.vault_path) / "Dashboard.md"

        if dashboard_path.exists():
            self.logger.debug("Dashboard.md already exists")
            return

        content = """# Dashboard

**Last Updated**: Not yet updated
**System Status**: Inactive

## Pending Actions (0)

No pending actions.

## Recent Activity

No recent activity.

## Quick Links

- [Needs Action](Needs_Action/)
- [Done](Done/)
- [Logs](Logs/)
- [Company Handbook](Company_Handbook.md)

## System Information

- **Vault Path**: {vault_path}
- **Check Interval**: {check_interval} seconds
- **Dry Run Mode**: {dry_run}

---
*Generated by Personal AI Employee (Bronze Tier)*
""".format(
            vault_path=self.vault_path,
            check_interval=self.check_interval,
            dry_run="Enabled" if self.dry_run else "Disabled"
        )

        dashboard_path.write_text(content, encoding='utf-8')
        self.logger.info("Created Dashboard.md template")

    def _create_handbook_template(self):
        """Create Company_Handbook.md if it doesn't exist."""
        handbook_path = Path(self.vault_path) / "Company_Handbook.md"

        if handbook_path.exists():
            self.logger.debug("Company_Handbook.md already exists")
            return

        content = """# Company Handbook

This handbook defines the rules and behaviors for your Personal AI Employee.

## Purpose

The AI Employee reads this handbook to understand how to process files, prioritize tasks, and make decisions on your behalf. Update these rules to customize the AI's behavior.

## General Rules

### File Processing
- Review all files within 24 hours of detection
- Flag any files over 10 MB for manual review
- Categorize files by type (invoice, contract, report, etc.)

### Prioritization
- Client communications are highest priority
- Financial documents require careful review
- Administrative tasks can be processed in batch

### Decision Making
- When in doubt, ask for human approval
- Never make financial commitments without approval
- Always log reasoning for decisions

## Specific Rules

### Invoices
- Flag all invoices over $500 for review
- Check for duplicate invoice numbers
- Verify payment terms and due dates
- Log to accounting folder

### Contracts
- All contracts require human review before signing
- Check for expiration dates and renewal terms
- Flag any unusual clauses or terms

### Client Communications
- Respond to client emails within 24 hours
- Maintain professional and friendly tone
- Escalate urgent requests immediately

### Reports
- Summarize key findings and recommendations
- Highlight any anomalies or concerns
- Archive completed reports to Done folder

## Custom Rules

Add your own rules here:

- [Your custom rule 1]
- [Your custom rule 2]
- [Your custom rule 3]

## Notes

- Rules are applied in order from top to bottom
- More specific rules override general rules
- Update this handbook as your needs evolve

---
*Last Updated*: {date}
""".format(date="2026-04-16")

        handbook_path.write_text(content, encoding='utf-8')
        self.logger.info("Created Company_Handbook.md template")

    def start(self):
        """Start the AI Employee system."""
        self.logger.info("=" * 60)
        self.logger.info("Personal AI Employee (Bronze Tier) Starting")
        self.logger.info("=" * 60)

        # Initialize vault
        self.initialize_vault()

        # Update dashboard with startup event
        self.vault_manager.update_dashboard("system_startup", {})

        # Create and start file watcher
        self.logger.info("Starting File Watcher")
        self.watcher = FileWatcher(
            vault_path=self.vault_path,
            logger=create_logger(self.vault_path, "FileWatcher", self.log_level),
            vault_manager=self.vault_manager,
            check_interval=self.check_interval
        )

        self.logger.info("=" * 60)
        self.logger.info("System is now running. Press Ctrl+C to stop.")
        self.logger.info("=" * 60)
        self.logger.info(f"Monitoring: {Path(self.vault_path) / 'Inbox'}")
        self.logger.info(f"Check interval: {self.check_interval} seconds")
        self.logger.info(f"Dry run mode: {'Enabled' if self.dry_run else 'Disabled'}")
        self.logger.info("=" * 60)

        # Start watcher (blocking)
        self.watcher.start()

    def shutdown(self):
        """Shutdown the AI Employee system."""
        self.logger.info("Shutting down AI Employee system")

        if self.watcher:
            self.watcher.stop()

        # Update dashboard with shutdown event
        try:
            dashboard_path = Path(self.vault_path) / "Dashboard.md"
            if dashboard_path.exists():
                content = dashboard_path.read_text(encoding='utf-8')
                content = content.replace("**System Status**: Active", "**System Status**: Inactive")
                dashboard_path.write_text(content, encoding='utf-8')
        except Exception as e:
            self.logger.error(f"Error updating dashboard on shutdown: {e}")

        self.logger.info("Shutdown complete")


def main():
    """Main entry point."""
    try:
        orchestrator = AIEmployeeOrchestrator()
        orchestrator.start()
    except KeyboardInterrupt:
        print("\nShutdown requested by user")
    except Exception as e:
        print(f"Fatal error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
